### ISSUE TITLE
Have you deployed this website...?

### ISSUE THREAD

**Issue by jainaman224** [GDGBVCOE/gdgwebsite#1]
This website is not hosted yet i think.

**Comment by satvik96** [comment]
No, not yet..

**Comment by poush** [comment]
No it is not. You can watch progress at https://gdgbvcoe.github.io/gdgwebsite/

**Comment by jainaman224** [comment]
Yes I have seen that but the way that site was working with slight changes in free html templates. I thought you are working privately. Therefore, I asked about it.
