### ISSUE TITLE
Things to complete for Phase 1 stable

### ISSUE THREAD

**Issue by poush** [GDGBVCOE/gdgwebsite#2]
- [x] Add Favicon
- [x] Update meta tags of social sites
  Add your points by replying here

**Comment by uday1201** [comment]
You need a design for the favicon?

**Comment by poush** [comment]
We can use some ico generator to create GDG logo's favicon

**Comment by poush** [comment]
We also need to update all Facebook and other social platform meta tags. Currently all are blank

**Comment by uday1201** [comment]
Only the last 2 ones are blank. One of fb n one of github.

**Comment by poush** [comment]
No I am saying about 
`<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> GDGBVP </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />`

these meta tags

**Comment by uday1201** [comment]
Ohh. Metatags. On it.

**Comment by uday1201** [comment]
meta tags done!
